/* ==========================================================================
   Boxel Studio Quoting Agent — Seed Data
   Real projects from boxelstudio.com/projects
   ========================================================================== */

const OPPORTUNITY_CATALOG = [
  "2D Comp",
  "3D Layout",
  "Animation",
  "CG Asset",
  "CG Environments",
  "CG Integration",
  "CG Scene for Virtual Production",
  "Character Animation",
  "Character Design",
  "Digi Double",
  "Environment Design",
  "FX",
  "On Set Supervision",
  "Rig",
  "Storyboard",
  "UE Previz"
];

const SEED_DATA = {
  projects: [
    {
      id: "the-muppet-show",
      title: "The Muppet Show",
      platform: "Disney+",
      category: "Animation",
      services: ["On Set Supervision", "CG Asset", "Animation", "2D Comp", "CG Integration"],
      thumbnail: "https://image.tmdb.org/t/p/w780/qz7B5uDspnkoz068wLbLnleotwV.jpg",
      dateAdded: "2026-02-18",
      gradientAngle: 135,
      gradientColors: ["#FFB700", "#9375C0"],
      totalCost: 485000,
      totalOpportunities: 7,
      totalScenes: 8,
      scenes: [
        {
          id: "ms-scene-1",
          name: "Opening Theater Curtain",
          duration: "45s",
          scriptPagesStart: 1,
          scriptPagesEnd: 4,
          estimatedLength: "45 sec",
          opportunities: 4,
          complexity: "medium",
          effortHours: 120,
          cost: 72000,
          status: "pending",
          scriptText: "FADE IN:\n\nINT. MUPPET THEATER - NIGHT\n\nThe velvet curtain rises slowly, revealing the iconic stage. KERMIT THE FROG stands center stage under a single spotlight.\n\nKERMIT\nIt's time to play the music...\nIt's time to light the lights...\n\nThe orchestra pit comes alive with ANIMAL on drums, crashing cymbals wildly. FOZZIE BEAR peeks from behind the curtain.\n\nFOZZIE\nWocka wocka! Are we live?\n\nSTATLER and WALDORF lean from their balcony box.\n\nSTATLER\nUnfortunately.\n\nWALDORF\nHo ho ho!",
          opportunityList: [
            { name: "On Set Supervision", selected: true, amount: 18000 },
            { name: "CG Asset", selected: true, amount: 18000 },
            { name: "Animation", selected: true, amount: 18000 },
            { name: "Character Animation", selected: false, amount: 0 },
            { name: "FX", selected: false, amount: 0 },
            { name: "2D Comp", selected: true, amount: 18000 },
            { name: "CG Integration", selected: false, amount: 0 }
          ],
        },
        {
          id: "ms-scene-2",
          name: "Backstage Chaos",
          duration: "30s",
          scriptPagesStart: 5,
          scriptPagesEnd: 8,
          estimatedLength: "30 sec",
          opportunities: 5,
          complexity: "high",
          effortHours: 95,
          cost: 58000,
          status: "pending",
          scriptText: "INT. BACKSTAGE - CONTINUOUS\n\nPandemonium. Props fly through the air. SCOOTER runs with a clipboard.\n\nSCOOTER\nFifteen seconds to curtain!\n\nGONZO rides past on a unicycle, juggling flaming torches. RIZZO THE RAT dodges a falling sandbag.\n\nRIZZO\nThis is no way to run a theater!\n\nMISS PIGGY sweeps through in an elaborate gown, knocking everyone aside.\n\nMISS PIGGY\nOut of my way! Star coming through!\n\nShe karate-chops a stagehand who doesn't move fast enough.",
          opportunityList: [
            { name: "On Set Supervision", selected: true, amount: 11600 },
            { name: "CG Asset", selected: true, amount: 11600 },
            { name: "Animation", selected: true, amount: 11600 },
            { name: "Character Animation", selected: false, amount: 0 },
            { name: "FX", selected: true, amount: 11600 },
            { name: "2D Comp", selected: true, amount: 11600 },
            { name: "CG Integration", selected: false, amount: 0 }
          ],
        },
        {
          id: "ms-scene-3",
          name: "Musical Number - Rainbow Connection",
          duration: "60s",
          scriptPagesStart: 9,
          scriptPagesEnd: 14,
          estimatedLength: "60 sec",
          opportunities: 5,
          complexity: "low",
          effortHours: 180,
          cost: 95000,
          status: "pending",
          scriptText: "INT. MUPPET THEATER STAGE - NIGHT\n\nThe stage transforms into a serene swamp setting. Fireflies (CGI) drift through the air. KERMIT sits on a log with his banjo.\n\nKERMIT\n(singing softly)\nWhy are there so many songs about rainbows...\nAnd what's on the other side?\n\nA magical rainbow materializes above the stage, shimmering with particle effects. The audience falls silent.\n\nKERMIT (CONT'D)\nRainbows are visions...\nBut only illusions...\n\nROBIN hops onto the log beside Kermit, joining in the harmony.",
          opportunityList: [
            { name: "On Set Supervision", selected: false, amount: 0 },
            { name: "CG Asset", selected: true, amount: 19000 },
            { name: "Animation", selected: true, amount: 19000 },
            { name: "Character Animation", selected: true, amount: 19000 },
            { name: "FX", selected: true, amount: 19000 },
            { name: "2D Comp", selected: true, amount: 19000 },
            { name: "CG Integration", selected: false, amount: 0 }
          ],
        },
        {
          id: "ms-scene-4",
          name: "Swedish Chef Kitchen Explosion",
          duration: "25s",
          scriptPagesStart: 15,
          scriptPagesEnd: 18,
          estimatedLength: "25 sec",
          opportunities: 4,
          complexity: "medium",
          effortHours: 85,
          cost: 52000,
          status: "pending",
          scriptText: "INT. MUPPET KITCHEN SET - NIGHT\n\nSWEDISH CHEF stands behind the counter with an absurdly large fish.\n\nSWEDISH CHEF\nBork bork bork!\n\nHe swings a cleaver. The fish dodges. Chaos ensues as ingredients fly everywhere. A pot boils over with green smoke (VFX).\n\nThe entire kitchen EXPLODES in a spectacular fireball (CG). Swedish Chef emerges, covered in soot, holding a perfectly plated dish.\n\nSWEDISH CHEF (CONT'D)\n(proudly)\nVoilà!",
          opportunityList: [
            { name: "On Set Supervision", selected: false, amount: 0 },
            { name: "CG Asset", selected: true, amount: 13000 },
            { name: "Animation", selected: true, amount: 13000 },
            { name: "Character Animation", selected: false, amount: 0 },
            { name: "FX", selected: true, amount: 13000 },
            { name: "2D Comp", selected: false, amount: 0 },
            { name: "CG Integration", selected: true, amount: 13000 }
          ],
        },
        {
          id: "ms-scene-5",
          name: "Pigs in Space",
          duration: "35s",
          scriptPagesStart: 19,
          scriptPagesEnd: 23,
          estimatedLength: "35 sec",
          opportunities: 5,
          complexity: "medium",
          effortHours: 110,
          cost: 68000,
          status: "pending",
          scriptText: "INT. SWINETREK BRIDGE - CONTINUOUS\n\nANNOUNCER (V.O.)\nAnd now... PIGS IN SPACE!\n\nCAPTAIN LINK HOGTHROB strikes a heroic pose. FIRST MATE PIGGY checks her makeup in a compact mirror. DR. STRANGEPORK fumbles with controls.\n\nLINK\nSteady as she goes!\n\nThe ship shakes violently (VFX). Stars streak past the viewscreen.\n\nPIGGY\nWe're under attack!\n\nAn asteroid field appears on screen. Link grabs the controls heroically, steering through the debris.\n\nSTRANGEPORK\nCaptain, I don't think that's how you--\n\nCRASH. The ship slams into an asteroid.",
          opportunityList: [
            { name: "On Set Supervision", selected: true, amount: 13600 },
            { name: "CG Asset", selected: true, amount: 13600 },
            { name: "Animation", selected: true, amount: 13600 },
            { name: "Character Animation", selected: false, amount: 0 },
            { name: "FX", selected: false, amount: 0 },
            { name: "2D Comp", selected: true, amount: 13600 },
            { name: "CG Integration", selected: true, amount: 13600 }
          ],
        },
        {
          id: "ms-scene-6",
          name: "Grand Finale Ensemble",
          duration: "50s",
          scriptPagesStart: 24,
          scriptPagesEnd: 30,
          estimatedLength: "50 sec",
          opportunities: 4,
          complexity: "low",
          effortHours: 150,
          cost: 85000,
          status: "pending",
          scriptText: "INT. MUPPET THEATER STAGE - NIGHT\n\nAll Muppets gather on stage for the closing number. Confetti cannons fire (VFX). Streamers fall from the rafters.\n\nENTIRE CAST\n(singing)\nWhy don't you get things started?\nIt's time to get things started\nOn the most sensational, inspirational\nCelebrational, Muppetational\nThis is what we call The Muppet Show!\n\nKERMIT\nThank you all for coming! See you next time on The Muppet Show!",
          opportunityList: [
            { name: "On Set Supervision", selected: true, amount: 21250 },
            { name: "CG Asset", selected: false, amount: 0 },
            { name: "Animation", selected: true, amount: 21250 },
            { name: "Character Animation", selected: true, amount: 21250 },
            { name: "FX", selected: false, amount: 0 },
            { name: "2D Comp", selected: true, amount: 21250 },
            { name: "CG Integration", selected: false, amount: 0 }
          ],
        },
        {
          id: "ms-scene-7",
          name: "Muppet Labs Incident",
          duration: "20s",
          scriptPagesStart: 31,
          scriptPagesEnd: 34,
          estimatedLength: "20 sec",
          opportunities: 3,
          complexity: "low",
          effortHours: 60,
          cost: 32000,
          status: "pending",
          scriptText: "INT. MUPPET LABS - DAY\n\nBUNSEN HONEYDEW stands beside a complicated machine.\n\nBUNSEN\nWelcome to Muppet Labs, where the future is being made today!\n\nBEAKER whimpers nervously beside him.\n\nBUNSEN (CONT'D)\nToday we're testing our new Digital Duplication Ray!\n\nHe pulls a lever. The machine hums, glows, and shoots a beam at Beaker. Suddenly there are THREE Beakers, all meeping in unison.\n\nBEAKERS\nMeep! Meep! Meep!",
          opportunityList: [
            { name: "On Set Supervision", selected: false, amount: 0 },
            { name: "CG Asset", selected: true, amount: 10667 },
            { name: "Animation", selected: true, amount: 10667 },
            { name: "Character Animation", selected: false, amount: 0 },
            { name: "FX", selected: false, amount: 0 },
            { name: "2D Comp", selected: false, amount: 0 },
            { name: "CG Integration", selected: true, amount: 10667 }
          ],
        },
        {
          id: "ms-scene-8",
          name: "Balcony Hecklers Closing",
          duration: "15s",
          scriptPagesStart: 35,
          scriptPagesEnd: 36,
          estimatedLength: "15 sec",
          opportunities: 3,
          complexity: "low",
          effortHours: 25,
          cost: 23000,
          status: "pending",
          scriptText: "INT. THEATER BALCONY - NIGHT\n\nSTATLER and WALDORF sit in their usual box seats as the theater empties.\n\nSTATLER\nWell, that was different.\n\nWALDORF\nDifferent how?\n\nSTATLER\nIt was worse than usual!\n\nBoth cackle. The lights fade.\n\nSTATLER & WALDORF\nDo-ho-ho-ho!\n\nFADE OUT.",
          opportunityList: [
            { name: "On Set Supervision", selected: true, amount: 7667 },
            { name: "CG Asset", selected: false, amount: 0 },
            { name: "Animation", selected: true, amount: 7667 },
            { name: "Character Animation", selected: false, amount: 0 },
            { name: "FX", selected: false, amount: 0 },
            { name: "2D Comp", selected: true, amount: 7667 },
            { name: "CG Integration", selected: false, amount: 0 }
          ],
        }
      ]
    },
    {
      id: "lincoln-lawyer-s4",
      title: "The Lincoln Lawyer S:4",
      platform: "Netflix",
      category: "VFX",
      thumbnail: "https://image.tmdb.org/t/p/w780/jBFOVEE5sMIyT141YIqIwyU8Y1D.jpg",
      dateAdded: "2026-01-10",
      services: ["On Set Supervision", "CG Asset", "2D Comp", "CG Integration"],
      gradientAngle: 200,
      gradientColors: ["#E85A4F", "#9375C0"],
      totalCost: 320000,
      totalOpportunities: 6,
      totalScenes: 6,
      scenes: [
        {
          id: "ll-scene-1",
          name: "Lincoln Continental Chase",
          duration: "40s",
          scriptPagesStart: 1,
          scriptPagesEnd: 6,
          estimatedLength: "40 sec",
          opportunities: 4,
          complexity: "medium",
          effortHours: 140,
          cost: 85000,
          status: "pending",
          scriptText: "EXT. LOS ANGELES STREETS - NIGHT\n\nMICKEY HALLER's Lincoln Continental tears through downtown LA. Rain slicks the streets (VFX enhancement).\n\nINT. LINCOLN CONTINENTAL - CONTINUOUS\n\nMickey grips the wheel. LORNA in the passenger seat clutches files.\n\nMICKEY\nWe need to get to the courthouse before they seal those records.\n\nLORNA\nMickey, you're going ninety!\n\nEXT. INTERSECTION - CONTINUOUS\n\nThe Lincoln runs a red light. A truck barely misses them (CG truck composited). Tires screech.",
          opportunityList: [
            { name: "On Set Supervision", selected: true, amount: 21250 },
            { name: "CG Asset", selected: true, amount: 21250 },
            { name: "Animation", selected: false, amount: 0 },
            { name: "Character Animation", selected: false, amount: 0 },
            { name: "FX", selected: false, amount: 0 },
            { name: "2D Comp", selected: true, amount: 21250 },
            { name: "CG Integration", selected: true, amount: 21250 }
          ],
        },
        {
          id: "ll-scene-2",
          name: "Courtroom Revelation",
          duration: "55s",
          scriptPagesStart: 7,
          scriptPagesEnd: 14,
          estimatedLength: "55 sec",
          opportunities: 3,
          complexity: "low",
          effortHours: 60,
          cost: 35000,
          status: "pending",
          scriptText: "INT. SUPERIOR COURT - DAY\n\nMickey stands before the jury. Behind him, a large screen displays evidence (VFX screen replacement).\n\nMICKEY\nLadies and gentlemen... what you're about to see changes everything.\n\nHe clicks a remote. Security footage plays — digitally enhanced and stabilized (2D Comp).\n\nJUDGE STANTON\nCounselor, where did you obtain this?\n\nMICKEY\nYour Honor, this was recovered from a traffic camera at Third and Spring.",
          opportunityList: [
            { name: "On Set Supervision", selected: true, amount: 11667 },
            { name: "CG Asset", selected: false, amount: 0 },
            { name: "Animation", selected: false, amount: 0 },
            { name: "Character Animation", selected: false, amount: 0 },
            { name: "FX", selected: false, amount: 0 },
            { name: "2D Comp", selected: true, amount: 11667 },
            { name: "CG Integration", selected: true, amount: 11667 }
          ],
        },
        {
          id: "ll-scene-3",
          name: "Rooftop Confrontation",
          duration: "35s",
          scriptPagesStart: 15,
          scriptPagesEnd: 20,
          estimatedLength: "35 sec",
          opportunities: 4,
          complexity: "medium",
          effortHours: 100,
          cost: 65000,
          status: "pending",
          scriptText: "EXT. DOWNTOWN LA ROOFTOP - NIGHT\n\nMickey steps onto the rooftop. The LA skyline stretches behind him (CG extension). Wind whips his suit.\n\nDETECTIVE GRIGGS steps from the shadows.\n\nGRIGGS\nYou should have left this alone, Haller.\n\nMICKEY\nI'm a defense attorney. Leaving things alone isn't in my vocabulary.\n\nGriggs pulls a gun. Mickey raises his hands slowly.\n\nMICKEY (CONT'D)\nYou sure you want to add another charge to your list?",
          opportunityList: [
            { name: "On Set Supervision", selected: false, amount: 0 },
            { name: "CG Asset", selected: true, amount: 16250 },
            { name: "Animation", selected: false, amount: 0 },
            { name: "Character Animation", selected: false, amount: 0 },
            { name: "FX", selected: true, amount: 16250 },
            { name: "2D Comp", selected: true, amount: 16250 },
            { name: "CG Integration", selected: true, amount: 16250 }
          ],
        },
        {
          id: "ll-scene-4",
          name: "Evidence Room Break-in",
          duration: "30s",
          scriptPagesStart: 21,
          scriptPagesEnd: 25,
          estimatedLength: "30 sec",
          opportunities: 3,
          complexity: "medium",
          effortHours: 80,
          cost: 48000,
          status: "pending",
          scriptText: "INT. POLICE EVIDENCE ROOM - NIGHT\n\nCISCO picks the lock with practiced ease. The door clicks open.\n\nINT. EVIDENCE ROOM - CONTINUOUS\n\nRows of shelves stretch into darkness. Cisco uses his phone flashlight (lighting VFX). He finds Box 4417.\n\nCISCO\n(into phone)\nMickey, I found it. Box 4417.\n\nMICKEY (O.S.)\nDon't open it there. Get out.\n\nAlarm sensors blink red in the corner (CG addition). Cisco grabs the box and moves.",
          opportunityList: [
            { name: "On Set Supervision", selected: false, amount: 0 },
            { name: "CG Asset", selected: true, amount: 16000 },
            { name: "Animation", selected: false, amount: 0 },
            { name: "Character Animation", selected: false, amount: 0 },
            { name: "FX", selected: false, amount: 0 },
            { name: "2D Comp", selected: true, amount: 16000 },
            { name: "CG Integration", selected: true, amount: 16000 }
          ],
        },
        {
          id: "ll-scene-5",
          name: "Sunset Beach Walk",
          duration: "25s",
          scriptPagesStart: 26,
          scriptPagesEnd: 29,
          estimatedLength: "25 sec",
          opportunities: 3,
          complexity: "low",
          effortHours: 50,
          cost: 42000,
          status: "pending",
          scriptText: "EXT. SANTA MONICA BEACH - SUNSET\n\nMickey and MAGGIE walk along the shore. The sunset paints the sky in oranges and purples (sky replacement VFX).\n\nMAGGIE\nYou won the case, Mickey. Why don't you look happy?\n\nMICKEY\nBecause winning shouldn't feel like this.\n\nWaves crash softly. Seagulls drift overhead (CG birds).\n\nMAGGIE\nHayley's proud of you. I'm proud of you.\n\nMickey manages a small smile.",
          opportunityList: [
            { name: "On Set Supervision", selected: true, amount: 14000 },
            { name: "CG Asset", selected: true, amount: 14000 },
            { name: "Animation", selected: false, amount: 0 },
            { name: "Character Animation", selected: false, amount: 0 },
            { name: "FX", selected: false, amount: 0 },
            { name: "2D Comp", selected: true, amount: 14000 },
            { name: "CG Integration", selected: false, amount: 0 }
          ],
        },
        {
          id: "ll-scene-6",
          name: "Final Verdict",
          duration: "20s",
          scriptPagesStart: 30,
          scriptPagesEnd: 33,
          estimatedLength: "20 sec",
          opportunities: 3,
          complexity: "low",
          effortHours: 40,
          cost: 45000,
          status: "pending",
          scriptText: "INT. SUPERIOR COURT - DAY\n\nThe courtroom is packed. Mickey stands beside his client.\n\nJUDGE STANTON\nHas the jury reached a verdict?\n\nFOREPERSON\nWe have, Your Honor. We find the defendant... not guilty.\n\nThe courtroom erupts. Mickey's client breaks down. Lorna hugs Mickey from behind the bar.\n\nMICKEY\n(whispered)\nThat's what justice looks like.",
          opportunityList: [
            { name: "On Set Supervision", selected: true, amount: 15000 },
            { name: "CG Asset", selected: false, amount: 0 },
            { name: "Animation", selected: false, amount: 0 },
            { name: "Character Animation", selected: false, amount: 0 },
            { name: "FX", selected: false, amount: 0 },
            { name: "2D Comp", selected: true, amount: 15000 },
            { name: "CG Integration", selected: true, amount: 15000 }
          ],
        }
      ]
    },
    {
      id: "kid-cowboy",
      title: "Kid Cowboy",
      platform: "Nickelodeon",
      category: "Animation",
      thumbnail: "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEjxIP8iCny_ChYjyRk6LDj1KZ9Bqy4kUWCXs2F5hVvss7wK8Q2zzDtQHOW4G3y8SoqL1P7p3cr2BH53qlI2-PhI2jWXkYx88PJ5luCI3h4ICQ80Zr5pf7IgYpFjCFy8RK4zhQjDx6GksSAG9jxOpY1ChVtqIQu3OG7N7bjhaAg8p80ESqoXE4bY/s1920/KCYT_105_003_070_Comp_v005.00_00_00_07.Still001.png",
      dateAdded: "2026-03-01",
      services: ["Storyboard", "3D Layout", "Rig", "Animation", "Character Animation", "2D Comp"],
      gradientAngle: 180,
      gradientColors: ["#FFB700", "#00EFD8"],
      totalCost: 275000,
      totalOpportunities: 7,
      totalScenes: 7,
      scenes: [
        {
          id: "kc-scene-1",
          name: "Sunrise on the Ranch",
          duration: "20s",
          scriptPagesStart: 1,
          scriptPagesEnd: 3,
          estimatedLength: "20 sec",
          opportunities: 3,
          complexity: "low",
          effortHours: 60,
          cost: 35000,
          status: "pending",
          scriptText: "EXT. DUSTY GULCH RANCH - DAWN\n\nThe sun peeks over cartoon mesas. Cacti cast long shadows. A rooster crows (badly).\n\nKID COWBOY (age 8) bursts from the bunkhouse, hat too big for his head, boots flopping.\n\nKID COWBOY\nYeehaw! Another day, another adventure!\n\nHis horse, BISCUIT (a tiny pony with attitude), is already saddled and unimpressed.\n\nBISCUIT\n(subtitled horse sounds)\nHere we go again...",
          opportunityList: [
            { name: "On Set Supervision", selected: false, amount: 0 },
            { name: "CG Asset", selected: false, amount: 0 },
            { name: "Animation", selected: true, amount: 11667 },
            { name: "Character Animation", selected: true, amount: 11667 },
            { name: "FX", selected: false, amount: 0 },
            { name: "2D Comp", selected: true, amount: 11667 },
            { name: "CG Integration", selected: false, amount: 0 }
          ],
        },
        {
          id: "kc-scene-2",
          name: "Lasso Training Gone Wrong",
          duration: "25s",
          scriptPagesStart: 4,
          scriptPagesEnd: 7,
          estimatedLength: "25 sec",
          opportunities: 4,
          complexity: "medium",
          effortHours: 80,
          cost: 45000,
          status: "pending",
          scriptText: "EXT. CORRAL - DAY\n\nKid Cowboy swings his lasso overhead. SHERIFF GRANNY watches from the fence.\n\nSHERIFF GRANNY\nRemember, sweetie — it's all in the wrist!\n\nKid throws the lasso. It wraps around his own feet. He spins, flies into the air, and lands on CACTUS PETE (a talking cactus).\n\nCACTUS PETE\nOw! Watch where you're landin', partner!\n\nKID COWBOY\nSorry, Pete! I'm still working on my technique!",
          opportunityList: [
            { name: "On Set Supervision", selected: false, amount: 0 },
            { name: "CG Asset", selected: true, amount: 11250 },
            { name: "Animation", selected: true, amount: 11250 },
            { name: "Character Animation", selected: true, amount: 11250 },
            { name: "FX", selected: false, amount: 0 },
            { name: "2D Comp", selected: true, amount: 11250 },
            { name: "CG Integration", selected: false, amount: 0 }
          ],
        },
        {
          id: "kc-scene-3",
          name: "Bandit Ambush at Gulch Bridge",
          duration: "35s",
          scriptPagesStart: 8,
          scriptPagesEnd: 13,
          estimatedLength: "35 sec",
          opportunities: 5,
          complexity: "high",
          effortHours: 110,
          cost: 62000,
          status: "pending",
          scriptText: "EXT. GULCH BRIDGE - DAY\n\nKid Cowboy rides Biscuit across the old wooden bridge. Suddenly, BANDIT BART and SNEAKY SAL block the path.\n\nBANDIT BART\nNobody crosses Gulch Bridge without paying the toll!\n\nKID COWBOY\nThis bridge is free for everyone, Bart!\n\nSNEAKY SAL\nNot anymore, little cowpoke.\n\nBiscuit rears up dramatically. Kid Cowboy pulls out his trusty water balloon launcher.\n\nKID COWBOY\nLast chance to move!\n\nA water balloon fight erupts across the bridge.",
          opportunityList: [
            { name: "On Set Supervision", selected: false, amount: 0 },
            { name: "CG Asset", selected: true, amount: 12400 },
            { name: "Animation", selected: true, amount: 12400 },
            { name: "Character Animation", selected: true, amount: 12400 },
            { name: "FX", selected: true, amount: 12400 },
            { name: "2D Comp", selected: true, amount: 12400 },
            { name: "CG Integration", selected: false, amount: 0 }
          ],
        },
        {
          id: "kc-scene-4",
          name: "Campfire Sing-Along",
          duration: "30s",
          scriptPagesStart: 14,
          scriptPagesEnd: 17,
          estimatedLength: "30 sec",
          opportunities: 4,
          complexity: "low",
          effortHours: 70,
          cost: 38000,
          status: "pending",
          scriptText: "EXT. CAMPSITE - NIGHT\n\nStars twinkle above. The gang sits around a campfire. Kid Cowboy strums a tiny guitar.\n\nKID COWBOY\n(singing)\nOh, give me a home where the buffalo roam...\n\nSHERIFF GRANNY joins in, surprisingly on key. DEPUTY DUSTY plays harmonica. Even Biscuit sways to the music.\n\nCACTUS PETE\nThis is the best part of any adventure — the end of it.\n\nEveryone laughs. Fireflies dance around them.",
          opportunityList: [
            { name: "On Set Supervision", selected: false, amount: 0 },
            { name: "CG Asset", selected: false, amount: 0 },
            { name: "Animation", selected: true, amount: 9500 },
            { name: "Character Animation", selected: true, amount: 9500 },
            { name: "FX", selected: true, amount: 9500 },
            { name: "2D Comp", selected: true, amount: 9500 },
            { name: "CG Integration", selected: false, amount: 0 }
          ],
        },
        {
          id: "kc-scene-5",
          name: "Mine Cart Escape",
          duration: "40s",
          scriptPagesStart: 18,
          scriptPagesEnd: 23,
          estimatedLength: "40 sec",
          opportunities: 5,
          complexity: "medium",
          effortHours: 120,
          cost: 55000,
          status: "pending",
          scriptText: "INT. ABANDONED GOLD MINE - DAY\n\nKid Cowboy and Deputy Dusty are trapped in a runaway mine cart. The tracks twist and loop.\n\nDEPUTY DUSTY\nHow do we stop this thing?!\n\nKID COWBOY\nWe don't stop it — we STEER it!\n\nKid grabs a wooden plank and uses it as a rudder. The cart jumps tracks, narrowly avoiding a boulder.\n\nBiscuit runs alongside the tracks outside, keeping pace.\n\nKID COWBOY (CONT'D)\nBiscuit! The switch! Pull the switch!\n\nBiscuit grabs the track switch lever in his teeth and yanks.",
          opportunityList: [
            { name: "On Set Supervision", selected: false, amount: 0 },
            { name: "CG Asset", selected: true, amount: 11000 },
            { name: "Animation", selected: true, amount: 11000 },
            { name: "Character Animation", selected: true, amount: 11000 },
            { name: "FX", selected: true, amount: 11000 },
            { name: "2D Comp", selected: true, amount: 11000 },
            { name: "CG Integration", selected: false, amount: 0 }
          ],
        },
        {
          id: "kc-scene-6",
          name: "Town Square Showdown",
          duration: "30s",
          scriptPagesStart: 24,
          scriptPagesEnd: 28,
          estimatedLength: "30 sec",
          opportunities: 4,
          complexity: "low",
          effortHours: 65,
          cost: 22000,
          status: "pending",
          scriptText: "EXT. DUSTY GULCH TOWN SQUARE - HIGH NOON\n\nTumbleweed rolls across the empty square. Kid Cowboy faces Bandit Bart across the dusty road.\n\nBANDIT BART\nThis town ain't big enough for the two of us.\n\nKID COWBOY\nYou're right. It's big enough for ALL of us.\n\nSheriff Granny, Deputy Dusty, and Cactus Pete step out from behind buildings, forming a line behind Kid.\n\nSHERIFF GRANNY\nYou heard the kid, Bart.",
          opportunityList: [
            { name: "On Set Supervision", selected: false, amount: 0 },
            { name: "CG Asset", selected: true, amount: 5500 },
            { name: "Animation", selected: true, amount: 5500 },
            { name: "Character Animation", selected: true, amount: 5500 },
            { name: "FX", selected: false, amount: 0 },
            { name: "2D Comp", selected: false, amount: 0 },
            { name: "CG Integration", selected: true, amount: 5500 }
          ],
        },
        {
          id: "kc-scene-7",
          name: "Sunset Ride Home",
          duration: "15s",
          scriptPagesStart: 29,
          scriptPagesEnd: 30,
          estimatedLength: "15 sec",
          opportunities: 3,
          complexity: "low",
          effortHours: 30,
          cost: 18000,
          status: "pending",
          scriptText: "EXT. DESERT TRAIL - SUNSET\n\nKid Cowboy rides Biscuit toward the setting sun. The sky is painted in oranges, pinks, and purples.\n\nKID COWBOY\nSame time tomorrow, Biscuit?\n\nBiscuit nods and whinnies happily.\n\nKID COWBOY (CONT'D)\nYeehaw!\n\nThey ride off into the sunset.\n\nFADE OUT.\n\nEND OF EPISODE",
          opportunityList: [
            { name: "On Set Supervision", selected: false, amount: 0 },
            { name: "CG Asset", selected: false, amount: 0 },
            { name: "Animation", selected: true, amount: 6000 },
            { name: "Character Animation", selected: true, amount: 6000 },
            { name: "FX", selected: false, amount: 0 },
            { name: "2D Comp", selected: true, amount: 6000 },
            { name: "CG Integration", selected: false, amount: 0 }
          ],
        }
      ]
    },
    {
      id: "g20",
      title: "G20",
      platform: "Prime Video",
      category: "VFX",
      thumbnail: "https://image.tmdb.org/t/p/w780/k32XKMjmXMGeydykD32jfER3BVI.jpg",
      dateAdded: "2025-12-05",
      services: ["CG Asset", "FX", "2D Comp", "CG Integration"],
      gradientAngle: 160,
      gradientColors: ["#6366F1", "#00EFD8"],
      totalCost: 520000,
      totalOpportunities: 7,
      totalScenes: 6,
      scenes: [
        {
          id: "g20-scene-1",
          name: "Summit Building Exterior",
          duration: "30s",
          scriptPagesStart: 1,
          scriptPagesEnd: 4,
          estimatedLength: "30 sec",
          opportunities: 4,
          complexity: "low",
          effortHours: 160,
          cost: 95000,
          status: "pending",
          scriptText: "EXT. BERLIN CONVENTION CENTER - DAY\n\nEstablishing shot. The massive glass-and-steel convention center gleams under gray skies. Security checkpoints line the perimeter. Military vehicles and diplomatic motorcades arrive in sequence.\n\nSUPER: 'BERLIN, GERMANY — G20 SUMMIT, DAY ONE'\n\nPRESIDENT CHEN exits a black SUV. Secret Service flanks her.\n\nCHEN\n(to aide)\nAny word from the Russian delegation?\n\nAIDE\nThey landed twenty minutes ago. Unusual route from the airport.",
          opportunityList: [
            { name: "On Set Supervision", selected: false, amount: 0 },
            { name: "CG Asset", selected: true, amount: 23750 },
            { name: "Animation", selected: false, amount: 0 },
            { name: "Character Animation", selected: false, amount: 0 },
            { name: "FX", selected: true, amount: 23750 },
            { name: "2D Comp", selected: true, amount: 23750 },
            { name: "CG Integration", selected: true, amount: 23750 }
          ],
        },
        {
          id: "g20-scene-2",
          name: "Control Room Breach",
          duration: "45s",
          scriptPagesStart: 5,
          scriptPagesEnd: 10,
          estimatedLength: "45 sec",
          opportunities: 5,
          complexity: "high",
          effortHours: 180,
          cost: 110000,
          status: "pending",
          scriptText: "INT. SECURITY CONTROL ROOM - DAY\n\nWalls of monitors display every angle of the summit. AGENT REEVES spots an anomaly.\n\nREEVES\nCamera seven just looped. Someone's feeding us old footage.\n\nShe types furiously. Code scrolls across her screen (CG screen graphics).\n\nREEVES (CONT'D)\nWe have a breach. All units, we have a breach!\n\nThe lights cut out. Emergency red lighting floods the room (VFX lighting transition). Monitors flicker and die one by one.\n\nDIRECTOR OKAFOR\n(into radio)\nLockdown. Full lockdown. NOW.",
          opportunityList: [
            { name: "On Set Supervision", selected: true, amount: 22000 },
            { name: "CG Asset", selected: true, amount: 22000 },
            { name: "Animation", selected: false, amount: 0 },
            { name: "Character Animation", selected: false, amount: 0 },
            { name: "FX", selected: true, amount: 22000 },
            { name: "2D Comp", selected: true, amount: 22000 },
            { name: "CG Integration", selected: true, amount: 22000 }
          ],
        },
        {
          id: "g20-scene-3",
          name: "Hostage Situation - Main Hall",
          duration: "60s",
          scriptPagesStart: 11,
          scriptPagesEnd: 18,
          estimatedLength: "60 sec",
          opportunities: 5,
          complexity: "medium",
          effortHours: 200,
          cost: 125000,
          status: "pending",
          scriptText: "INT. MAIN SUMMIT HALL - DAY\n\nWorld leaders sit around the massive circular table. Suddenly, armored figures rappel through the skylights (CG glass shattering, rope VFX).\n\nLeader of the group, RAVEN, lands center stage. Gas canisters deploy (FX smoke simulation).\n\nRAVEN\nLadies and gentlemen... this summit just changed its agenda.\n\nPanic. Security draws weapons. A firefight erupts. Bullets spark off the marble columns (muzzle flash VFX, bullet impacts).\n\nCHEN\n(ducking under table)\nGet me a secure line to Washington!",
          opportunityList: [
            { name: "On Set Supervision", selected: false, amount: 0 },
            { name: "CG Asset", selected: true, amount: 25000 },
            { name: "Animation", selected: true, amount: 25000 },
            { name: "Character Animation", selected: false, amount: 0 },
            { name: "FX", selected: true, amount: 25000 },
            { name: "2D Comp", selected: true, amount: 25000 },
            { name: "CG Integration", selected: true, amount: 25000 }
          ],
        },
        {
          id: "g20-scene-4",
          name: "Ventilation Shaft Crawl",
          duration: "25s",
          scriptPagesStart: 19,
          scriptPagesEnd: 22,
          estimatedLength: "25 sec",
          opportunities: 3,
          complexity: "medium",
          effortHours: 90,
          cost: 55000,
          status: "pending",
          scriptText: "INT. VENTILATION SYSTEM - DAY\n\nAgent Reeves crawls through tight metal ducts. Sweat drips from her face. She checks a holographic map on her smartwatch (CG hologram).\n\nREEVES\n(whispering into comms)\nI'm above the server room. Two hostiles guarding the door.\n\nOKAFOR (V.O.)\nCan you get a visual?\n\nReeves peers through a vent grate. Below, two armed guards patrol.\n\nREEVES\nAffirmative. Moving to position.",
          opportunityList: [
            { name: "On Set Supervision", selected: false, amount: 0 },
            { name: "CG Asset", selected: true, amount: 18333 },
            { name: "Animation", selected: false, amount: 0 },
            { name: "Character Animation", selected: false, amount: 0 },
            { name: "FX", selected: false, amount: 0 },
            { name: "2D Comp", selected: true, amount: 18333 },
            { name: "CG Integration", selected: true, amount: 18333 }
          ],
        },
        {
          id: "g20-scene-5",
          name: "Explosion on East Wing",
          duration: "20s",
          scriptPagesStart: 23,
          scriptPagesEnd: 26,
          estimatedLength: "20 sec",
          opportunities: 4,
          complexity: "medium",
          effortHours: 150,
          cost: 90000,
          status: "pending",
          scriptText: "EXT. CONVENTION CENTER - EAST WING - DAY\n\nA massive explosion rocks the east wing (full CG destruction sequence). Glass, steel, and debris fly outward. The shockwave ripples through parked vehicles.\n\nINT. MAIN HALL - CONTINUOUS\n\nThe building shakes. Dust falls from the ceiling. World leaders scream.\n\nRAVEN\n(into radio)\nThat was just the appetizer.\n\nCHEN\n(to PM Williams)\nWe need to move. Now.",
          opportunityList: [
            { name: "On Set Supervision", selected: false, amount: 0 },
            { name: "CG Asset", selected: true, amount: 22500 },
            { name: "Animation", selected: false, amount: 0 },
            { name: "Character Animation", selected: false, amount: 0 },
            { name: "FX", selected: true, amount: 22500 },
            { name: "2D Comp", selected: true, amount: 22500 },
            { name: "CG Integration", selected: true, amount: 22500 }
          ],
        },
        {
          id: "g20-scene-6",
          name: "Rooftop Helicopter Escape",
          duration: "35s",
          scriptPagesStart: 27,
          scriptPagesEnd: 32,
          estimatedLength: "35 sec",
          opportunities: 4,
          complexity: "low",
          effortHours: 130,
          cost: 45000,
          status: "pending",
          scriptText: "EXT. CONVENTION CENTER ROOFTOP - DAY\n\nAgent Reeves leads President Chen and PM Williams to the rooftop. Wind from approaching helicopters (CG) whips their clothes.\n\nTwo military helicopters descend. Raven appears from the stairwell behind them.\n\nRAVEN\nYou didn't think it would be that easy?\n\nReeves pushes Chen toward the helicopter.\n\nREEVES\nGo! Get the President out!\n\nShe turns to face Raven alone. The helicopter lifts off behind her.",
          opportunityList: [
            { name: "On Set Supervision", selected: true, amount: 11250 },
            { name: "CG Asset", selected: true, amount: 11250 },
            { name: "Animation", selected: false, amount: 0 },
            { name: "Character Animation", selected: true, amount: 11250 },
            { name: "FX", selected: false, amount: 0 },
            { name: "2D Comp", selected: false, amount: 0 },
            { name: "CG Integration", selected: true, amount: 11250 }
          ],
        }
      ]
    },
    {
      id: "mythic-quest-s4",
      title: "Mythic Quest S:4",
      platform: "Apple TV",
      category: "VFX",
      services: ["CG Asset", "2D Comp"],
      thumbnail: "https://image.tmdb.org/t/p/w780/cP82Jtvn7DwVt0mWaDFm7QhWHez.jpg",
      dateAdded: "2026-01-25",
      gradientAngle: 225,
      gradientColors: ["#32D583", "#6366F1"],
      totalCost: 185000,
      totalOpportunities: 5,
      totalScenes: 5,
      scenes: [
        {
          id: "mq-scene-1",
          name: "Game World - Dragon Battle",
          duration: "30s",
          scriptPagesStart: 1,
          scriptPagesEnd: 5,
          estimatedLength: "30 sec",
          opportunities: 4,
          complexity: "medium",
          effortHours: 90,
          cost: 55000,
          status: "pending",
          scriptText: "INT. MYTHIC QUEST GAME WORLD - DAY (CGI)\n\nA vast fantasy landscape. Two players battle a DRAGON atop a crystal mountain. Lightning crackles. The dragon breathes blue fire.\n\nPLAYER 1 AVATAR\nUse the Frost Shield!\n\nPLAYER 2 AVATAR\nI sold the Frost Shield for that hat!\n\nThe dragon sweeps its tail, sending Player 2 flying.\n\nCUT TO:\n\nINT. IAN'S OFFICE - DAY\n\nIAN GRIMM watches the gameplay on his monitor, mortified.\n\nIAN\nWho approved that hat?",
          opportunityList: [
            { name: "On Set Supervision", selected: false, amount: 0 },
            { name: "CG Asset", selected: true, amount: 13750 },
            { name: "Animation", selected: true, amount: 13750 },
            { name: "Character Animation", selected: false, amount: 0 },
            { name: "FX", selected: true, amount: 13750 },
            { name: "2D Comp", selected: true, amount: 13750 },
            { name: "CG Integration", selected: false, amount: 0 }
          ],
        },
        {
          id: "mq-scene-2",
          name: "Office Launch Party",
          duration: "25s",
          scriptPagesStart: 6,
          scriptPagesEnd: 9,
          estimatedLength: "25 sec",
          opportunities: 3,
          complexity: "low",
          effortHours: 30,
          cost: 18000,
          status: "pending",
          scriptText: "INT. MYTHIC QUEST OFFICES - NIGHT\n\nThe office is decorated for a launch party. Screens display the new expansion trailer (VFX screen content). Confetti cannons fire.\n\nPOPPY\nLaunch numbers are... incredible.\n\nIAN\n(false modesty)\nWell, I don't like to say I told you so...\n\nDAVID\nYou literally said 'I told you so' in the company Slack.\n\nBRAD\nThree times.\n\nIAN\nCreativity requires confidence, David.",
          opportunityList: [
            { name: "On Set Supervision", selected: false, amount: 0 },
            { name: "CG Asset", selected: true, amount: 6000 },
            { name: "Animation", selected: false, amount: 0 },
            { name: "Character Animation", selected: false, amount: 0 },
            { name: "FX", selected: false, amount: 0 },
            { name: "2D Comp", selected: true, amount: 6000 },
            { name: "CG Integration", selected: true, amount: 6000 }
          ],
        },
        {
          id: "mq-scene-3",
          name: "Game World - Underwater Temple",
          duration: "40s",
          scriptPagesStart: 10,
          scriptPagesEnd: 14,
          estimatedLength: "40 sec",
          opportunities: 4,
          complexity: "medium",
          effortHours: 120,
          cost: 65000,
          status: "pending",
          scriptText: "INT. MYTHIC QUEST GAME WORLD - UNDERWATER TEMPLE (CGI)\n\nA breathtaking underwater sequence. Coral reefs glow with bioluminescence. Ancient stone pillars rise from the ocean floor.\n\nA lone player avatar swims through the temple entrance. Fish scatter. Light beams pierce the water from above.\n\nThe camera pulls back to reveal the enormous scale of the temple — it stretches for miles in every direction.\n\nCUT TO:\n\nINT. POPPY'S OFFICE - DAY\n\nPoppy watches, tears in her eyes.\n\nPOPPY\nIt's exactly how I imagined it.",
          opportunityList: [
            { name: "On Set Supervision", selected: false, amount: 0 },
            { name: "CG Asset", selected: true, amount: 16250 },
            { name: "Animation", selected: true, amount: 16250 },
            { name: "Character Animation", selected: false, amount: 0 },
            { name: "FX", selected: true, amount: 16250 },
            { name: "2D Comp", selected: true, amount: 16250 },
            { name: "CG Integration", selected: false, amount: 0 }
          ],
        },
        {
          id: "mq-scene-4",
          name: "Server Room Crisis",
          duration: "20s",
          scriptPagesStart: 15,
          scriptPagesEnd: 18,
          estimatedLength: "20 sec",
          opportunities: 3,
          complexity: "low",
          effortHours: 40,
          cost: 25000,
          status: "pending",
          scriptText: "INT. SERVER ROOM - NIGHT\n\nRed warning lights flash across rows of servers. CAROL rushes in with David.\n\nCAROL\nWe're losing servers! The expansion is overloading everything!\n\nDAVID\nHow many players?\n\nCAROL\nTwo million. Simultaneously. Our infrastructure supports eight hundred thousand.\n\nDavid pulls out his phone.\n\nDAVID\nI'm calling AWS. And Poppy. In that order.\n\nCAROL\nReally? AWS first?\n\nDAVID\nAWS won't yell at me.",
          opportunityList: [
            { name: "On Set Supervision", selected: false, amount: 0 },
            { name: "CG Asset", selected: true, amount: 8333 },
            { name: "Animation", selected: false, amount: 0 },
            { name: "Character Animation", selected: false, amount: 0 },
            { name: "FX", selected: false, amount: 0 },
            { name: "2D Comp", selected: true, amount: 8333 },
            { name: "CG Integration", selected: true, amount: 8333 }
          ],
        },
        {
          id: "mq-scene-5",
          name: "Award Show Acceptance",
          duration: "15s",
          scriptPagesStart: 19,
          scriptPagesEnd: 21,
          estimatedLength: "15 sec",
          opportunities: 3,
          complexity: "low",
          effortHours: 25,
          cost: 22000,
          status: "pending",
          scriptText: "INT. GAME AWARDS CEREMONY - NIGHT\n\nSpotlights sweep the audience. A giant screen displays 'GAME OF THE YEAR: MYTHIC QUEST' (VFX screen content).\n\nIAN and POPPY walk to the podium together. The audience applauds.\n\nIAN\nI'd like to thank... myself, primarily.\n\nPOPPY\n(taking the mic)\nHe means the team. The incredible, overworked, underpaid team.\n\nIAN\nI also mean myself.\n\nLaughter from the audience.",
          opportunityList: [
            { name: "On Set Supervision", selected: true, amount: 7333 },
            { name: "CG Asset", selected: true, amount: 7333 },
            { name: "Animation", selected: false, amount: 0 },
            { name: "Character Animation", selected: false, amount: 0 },
            { name: "FX", selected: false, amount: 0 },
            { name: "2D Comp", selected: true, amount: 7333 },
            { name: "CG Integration", selected: false, amount: 0 }
          ],
        }
      ]
    },
    {
      id: "the-hunting-party",
      title: "The Hunting Party",
      platform: "Peacock",
      category: "VFX",
      services: ["CG Asset", "CG Environments", "FX", "2D Comp", "CG Integration"],
      thumbnail: "https://image.tmdb.org/t/p/w780/mP3bH1RdN1yCbUxrcQbCzFtIOaR.jpg",
      dateAdded: "2026-02-28",
      gradientAngle: 300,
      gradientColors: ["#E85A4F", "#FFB700"],
      totalCost: 410000,
      totalOpportunities: 7,
      totalScenes: 6,
      scenes: [
        {
          id: "hp-scene-1",
          name: "Forest Pursuit Opening",
          duration: "45s",
          scriptPagesStart: 1,
          scriptPagesEnd: 6,
          estimatedLength: "45 sec",
          opportunities: 5,
          complexity: "medium",
          effortHours: 140,
          cost: 88000,
          status: "pending",
          scriptText: "EXT. PACIFIC NORTHWEST FOREST - DAWN\n\nDense fog weaves through ancient trees (CG fog enhancement). A FIGURE crashes through underbrush, breathing hard.\n\nELENA MARSH, 30s, ex-military, sprints through the forest. Blood on her sleeve. Branches whip her face.\n\nBehind her — distant flashlights sweep through the fog. Dogs bark.\n\nELENA\n(into earpiece)\nThey found me. North ridge, heading for the river.\n\nBASE (V.O.)\nCopy. Extraction in twenty minutes.\n\nELENA\nI don't have twenty minutes.\n\nShe slides down a muddy slope (environment VFX).",
          opportunityList: [
            { name: "On Set Supervision", selected: false, amount: 0 },
            { name: "CG Asset", selected: true, amount: 22000 },
            { name: "Animation", selected: false, amount: 0 },
            { name: "Character Animation", selected: false, amount: 0 },
            { name: "FX", selected: true, amount: 22000 },
            { name: "2D Comp", selected: true, amount: 22000 },
            { name: "CG Integration", selected: true, amount: 22000 }
          ],
        },
        {
          id: "hp-scene-2",
          name: "Cabin Briefing",
          duration: "30s",
          scriptPagesStart: 7,
          scriptPagesEnd: 11,
          estimatedLength: "30 sec",
          opportunities: 3,
          complexity: "low",
          effortHours: 50,
          cost: 32000,
          status: "pending",
          scriptText: "INT. REMOTE CABIN - NIGHT\n\nA worn map covers the table. Elena sits with her team: JACK (the strategist), MAYA (tech specialist), and TORRES (muscle).\n\nJACK\nThe target compound is here. Private land, no public records. Satellite shows heat signatures for approximately thirty occupants.\n\nMAYA\nTheir comms are encrypted. Military-grade.\n\nTORRES\nSo we're dealing with pros.\n\nELENA\nWe knew that going in. The question is — what are they hunting?",
          opportunityList: [
            { name: "On Set Supervision", selected: true, amount: 10667 },
            { name: "CG Asset", selected: true, amount: 10667 },
            { name: "Animation", selected: false, amount: 0 },
            { name: "Character Animation", selected: false, amount: 0 },
            { name: "FX", selected: false, amount: 0 },
            { name: "2D Comp", selected: true, amount: 10667 },
            { name: "CG Integration", selected: false, amount: 0 }
          ],
        },
        {
          id: "hp-scene-3",
          name: "Compound Infiltration",
          duration: "50s",
          scriptPagesStart: 12,
          scriptPagesEnd: 18,
          estimatedLength: "50 sec",
          opportunities: 5,
          complexity: "high",
          effortHours: 180,
          cost: 115000,
          status: "pending",
          scriptText: "EXT. COMPOUND PERIMETER - NIGHT\n\nElena and Torres cut through a chain-link fence. Night vision POV (VFX overlay).\n\nELENA\n(hand signals)\nTwo guards. East tower.\n\nTorres nods. They move like shadows.\n\nINT. COMPOUND BUILDING - CONTINUOUS\n\nMaya's voice guides them through comms as she hacks the security grid (CG screen graphics for Maya's POV).\n\nMAYA (V.O.)\nTurning cameras off in three... two... one. You have ninety seconds.\n\nElena and Torres slip inside. The corridor stretches ahead — industrial, cold, lit by flickering fluorescents (lighting VFX).",
          opportunityList: [
            { name: "On Set Supervision", selected: true, amount: 23000 },
            { name: "CG Asset", selected: true, amount: 23000 },
            { name: "Animation", selected: false, amount: 0 },
            { name: "Character Animation", selected: false, amount: 0 },
            { name: "FX", selected: true, amount: 23000 },
            { name: "2D Comp", selected: true, amount: 23000 },
            { name: "CG Integration", selected: true, amount: 23000 }
          ],
        },
        {
          id: "hp-scene-4",
          name: "River Crossing Under Fire",
          duration: "35s",
          scriptPagesStart: 19,
          scriptPagesEnd: 23,
          estimatedLength: "35 sec",
          opportunities: 4,
          complexity: "medium",
          effortHours: 120,
          cost: 75000,
          status: "pending",
          scriptText: "EXT. MOUNTAIN RIVER - NIGHT\n\nRaging rapids. Elena wades across, water chest-high. Torres follows. Gunfire erupts from the treeline (muzzle flash VFX).\n\nBullets splash the water around them. Elena ducks under. Surfaces.\n\nELENA\nMove! Don't stop!\n\nTORRES\n(hit in the shoulder)\nI'm hit!\n\nElena grabs him. Drags him through the current. The river roars (CG water enhancement).\n\nJACK (V.O.)\nI've got suppressive fire from the ridge. Keep moving!",
          opportunityList: [
            { name: "On Set Supervision", selected: false, amount: 0 },
            { name: "CG Asset", selected: true, amount: 18750 },
            { name: "Animation", selected: false, amount: 0 },
            { name: "Character Animation", selected: false, amount: 0 },
            { name: "FX", selected: true, amount: 18750 },
            { name: "2D Comp", selected: true, amount: 18750 },
            { name: "CG Integration", selected: true, amount: 18750 }
          ],
        },
        {
          id: "hp-scene-5",
          name: "Helicopter Extraction",
          duration: "25s",
          scriptPagesStart: 24,
          scriptPagesEnd: 27,
          estimatedLength: "25 sec",
          opportunities: 4,
          complexity: "low",
          effortHours: 80,
          cost: 52000,
          status: "pending",
          scriptText: "EXT. FOREST CLEARING - DAWN\n\nA helicopter descends through the mist (CG helicopter). Rotor wash flattens the grass. Elena supports the wounded Torres.\n\nJACK\n(running ahead)\nBird's here! Let's go!\n\nThey pile in. Maya is already inside with a laptop.\n\nMAYA\nI got the data. Everything we need.\n\nElena looks back at the forest. Smoke rises in the distance.\n\nELENA\nWe'll be back.\n\nThe helicopter lifts off and disappears into the clouds.",
          opportunityList: [
            { name: "On Set Supervision", selected: false, amount: 0 },
            { name: "CG Asset", selected: true, amount: 13000 },
            { name: "Animation", selected: true, amount: 13000 },
            { name: "Character Animation", selected: false, amount: 0 },
            { name: "FX", selected: false, amount: 0 },
            { name: "2D Comp", selected: true, amount: 13000 },
            { name: "CG Integration", selected: true, amount: 13000 }
          ],
        },
        {
          id: "hp-scene-6",
          name: "Evidence Revelation",
          duration: "20s",
          scriptPagesStart: 28,
          scriptPagesEnd: 30,
          estimatedLength: "20 sec",
          opportunities: 3,
          complexity: "low",
          effortHours: 30,
          cost: 48000,
          status: "pending",
          scriptText: "INT. SAFE HOUSE - DAY\n\nElena and Maya study the stolen data on multiple screens (CG screen graphics). Photos, documents, financial records.\n\nMAYA\nElena... look at this.\n\nShe pulls up a photo. Elena's face drains of color.\n\nELENA\nThat's... that's impossible.\n\nMAYA\nIt goes all the way to the top.\n\nElena stares at the screen. Her hand trembles.\n\nELENA\nCall everyone in. We're going to need a bigger team.\n\nSMASH CUT TO BLACK.\n\nEND OF EPISODE.",
          opportunityList: [
            { name: "On Set Supervision", selected: false, amount: 0 },
            { name: "CG Asset", selected: true, amount: 16000 },
            { name: "Animation", selected: false, amount: 0 },
            { name: "Character Animation", selected: false, amount: 0 },
            { name: "FX", selected: false, amount: 0 },
            { name: "2D Comp", selected: true, amount: 16000 },
            { name: "CG Integration", selected: true, amount: 16000 }
          ],
        }
      ]
    },
    {
      id: "stranger-things-s5",
      title: "Stranger Things S:5",
      platform: "Netflix",
      category: "VFX",
      services: ["CG Asset", "CG Environments", "FX", "2D Comp", "CG Integration"],
      thumbnail: "https://image.tmdb.org/t/p/w780/8zbAoryWbtH0DKdev8abFAjdufy.jpg",
      dateAdded: "2026-03-10",
      gradientAngle: 180,
      gradientColors: ["#E85A4F", "#1A1A2E"],
      totalCost: 720000,
      totalOpportunities: 7,
      totalScenes: 7,
      scenes: [
        {
          id: "st-scene-1",
          name: "Upside Down Portal Opening",
          duration: "50s",
          scriptPagesStart: 1,
          scriptPagesEnd: 6,
          estimatedLength: "50 sec",
          opportunities: 5,
          complexity: "medium",
          effortHours: 200,
          cost: 145000,
          status: "pending",
          scriptText: "EXT. HAWKINS TOWN SQUARE - NIGHT\n\nThe ground trembles. Cracks spider-web across the asphalt, glowing red from below.\n\nELEVEN stands in the center, nose bleeding, hands raised.\n\nELEVEN\nIt's coming.\n\nMIKE\nEl, we need to go!\n\nThe sky tears open — a massive rift revealing the Upside Down. Particle debris rains down. Buildings shake.\n\nDUSTIN\n(into walkie)\nCode Red! This is a Code Red!\n\nLUCAS\nEveryone off the streets! NOW!",
          opportunityList: [
            { name: "On Set Supervision", selected: false, amount: 0 },
            { name: "CG Asset", selected: true, amount: 29000 },
            { name: "Animation", selected: true, amount: 29000 },
            { name: "Character Animation", selected: false, amount: 0 },
            { name: "FX", selected: true, amount: 29000 },
            { name: "2D Comp", selected: true, amount: 29000 },
            { name: "CG Integration", selected: true, amount: 29000 }
          ],
        },
        {
          id: "st-scene-2",
          name: "Lab Flashback",
          duration: "30s",
          scriptPagesStart: 7,
          scriptPagesEnd: 10,
          estimatedLength: "30 sec",
          opportunities: 3,
          complexity: "low",
          effortHours: 80,
          cost: 55000,
          status: "pending",
          scriptText: "INT. HAWKINS NATIONAL LABORATORY - 1979 (FLASHBACK)\n\nSterile white corridors. DR. BRENNER walks with a young ELEVEN, age 5.\n\nBRENNER\nYou're special, Eleven. More special than you know.\n\nYoung Eleven looks at a one-way mirror. Behind it, other children with shaved heads sit in a circle.\n\nBRENNER\nToday we're going to try something new.\n\nHe places his hand on her shoulder. She flinches.",
          opportunityList: [
            { name: "On Set Supervision", selected: true, amount: 18333 },
            { name: "CG Asset", selected: true, amount: 18333 },
            { name: "Animation", selected: false, amount: 0 },
            { name: "Character Animation", selected: false, amount: 0 },
            { name: "FX", selected: false, amount: 0 },
            { name: "2D Comp", selected: true, amount: 18333 },
            { name: "CG Integration", selected: false, amount: 0 }
          ],
        },
        {
          id: "st-scene-3",
          name: "Vecna's Lair",
          duration: "45s",
          scriptPagesStart: 11,
          scriptPagesEnd: 16,
          estimatedLength: "45 sec",
          opportunities: 5,
          complexity: "medium",
          effortHours: 180,
          cost: 130000,
          status: "pending",
          scriptText: "INT. UPSIDE DOWN - VECNA'S LAIR - CONTINUOUS\n\nTendrils of organic matter pulse along the walls. VECNA hovers above a throne of twisted vines, eyes glowing.\n\nVECNA\nYou thought you could stop me. But I am Hawkins. I am the shadow that was always here.\n\nELEVEN steps forward, energy crackling around her fists.\n\nELEVEN\nYou're nothing. You're just Henry.\n\nVecna snarls. The room shakes. Vines lash out toward Eleven.",
          opportunityList: [
            { name: "On Set Supervision", selected: false, amount: 0 },
            { name: "CG Asset", selected: true, amount: 26000 },
            { name: "Animation", selected: true, amount: 26000 },
            { name: "Character Animation", selected: true, amount: 26000 },
            { name: "FX", selected: true, amount: 26000 },
            { name: "2D Comp", selected: true, amount: 26000 },
            { name: "CG Integration", selected: false, amount: 0 }
          ],
        },
        {
          id: "st-scene-4",
          name: "Demogorgon Pack Attack",
          duration: "40s",
          scriptPagesStart: 17,
          scriptPagesEnd: 21,
          estimatedLength: "40 sec",
          opportunities: 5,
          complexity: "high",
          effortHours: 160,
          cost: 120000,
          status: "pending",
          scriptText: "EXT. HAWKINS HIGH SCHOOL - NIGHT\n\nA PACK OF DEMOGORGONS swarms across the football field. STEVE leads the defense with a nail bat.\n\nSTEVE\nRemember — aim for the face!\n\nROBIN\nThey don't really have faces, Steve!\n\nNANCY fires a shotgun. A Demogorgon staggers back. Another leaps from the bleachers.\n\nJONATHAN\nBehind you!\n\nSteve spins, bat connecting with a sickening crack.",
          opportunityList: [
            { name: "On Set Supervision", selected: false, amount: 0 },
            { name: "CG Asset", selected: true, amount: 24000 },
            { name: "Animation", selected: true, amount: 24000 },
            { name: "Character Animation", selected: true, amount: 24000 },
            { name: "FX", selected: true, amount: 24000 },
            { name: "2D Comp", selected: false, amount: 0 },
            { name: "CG Integration", selected: true, amount: 24000 }
          ],
        },
        {
          id: "st-scene-5",
          name: "Mind Flayer Rising",
          duration: "35s",
          scriptPagesStart: 22,
          scriptPagesEnd: 25,
          estimatedLength: "35 sec",
          opportunities: 4,
          complexity: "medium",
          effortHours: 140,
          cost: 105000,
          status: "pending",
          scriptText: "EXT. HAWKINS - AERIAL SHOT - NIGHT\n\nThe camera pulls back to reveal the entire town. From the rift, a massive shadow rises — the MIND FLAYER in its full form, towering over buildings.\n\nDUSTIN\n(looking up)\nOh no. Oh no no no.\n\nMIKE\nIt's bigger than before.\n\nELEVEN\nI know what I have to do.\n\nShe walks toward the creature alone. Mike reaches for her.\n\nMIKE\nEl, don't—\n\nShe looks back. A single tear.\n\nELEVEN\nClose the gate behind me.",
          opportunityList: [
            { name: "On Set Supervision", selected: false, amount: 0 },
            { name: "CG Asset", selected: true, amount: 26250 },
            { name: "Animation", selected: false, amount: 0 },
            { name: "Character Animation", selected: false, amount: 0 },
            { name: "FX", selected: true, amount: 26250 },
            { name: "2D Comp", selected: true, amount: 26250 },
            { name: "CG Integration", selected: true, amount: 26250 }
          ],
        },
        {
          id: "st-scene-6",
          name: "Hawkins Destruction Montage",
          duration: "25s",
          scriptPagesStart: 26,
          scriptPagesEnd: 28,
          estimatedLength: "25 sec",
          opportunities: 4,
          complexity: "low",
          effortHours: 100,
          cost: 80000,
          status: "pending",
          scriptText: "MONTAGE - HAWKINS FALLING\n\nRapid cuts: The Starcourt Mall collapses into a sinkhole. The Wheeler house splits in half. Hawkins Lab crumbles.\n\nCitizens flee in their cars. Military helicopters circle overhead.\n\nJOYCE clutches WILL, running. HOPPER provides cover fire.\n\nHOPPER\nKeep moving! Don't look back!\n\nThe rift expands. The Upside Down bleeds into reality.",
          opportunityList: [
            { name: "On Set Supervision", selected: true, amount: 20000 },
            { name: "CG Asset", selected: true, amount: 20000 },
            { name: "Animation", selected: false, amount: 0 },
            { name: "Character Animation", selected: false, amount: 0 },
            { name: "FX", selected: true, amount: 20000 },
            { name: "2D Comp", selected: true, amount: 20000 },
            { name: "CG Integration", selected: false, amount: 0 }
          ],
        },
        {
          id: "st-scene-7",
          name: "Final Sacrifice",
          duration: "30s",
          scriptPagesStart: 29,
          scriptPagesEnd: 32,
          estimatedLength: "30 sec",
          opportunities: 4,
          complexity: "low",
          effortHours: 120,
          cost: 85000,
          status: "pending",
          scriptText: "INT. UPSIDE DOWN - THE RIFT - CONTINUOUS\n\nEleven floats at the center of the rift, energy swirling around her. Her body glows.\n\nELEVEN (V.O.)\nI remember now. I remember everything.\n\nFlashbacks cascade: her childhood, her friends, Hopper's cabin, Mike's hand in hers.\n\nThe rift begins to close. Light floods the darkness.\n\nEXT. HAWKINS - CONTINUOUS\n\nThe group watches as the sky heals. Dawn breaks over a ruined but saved Hawkins.\n\nMIKE\n(whispering)\nShe did it.",
          opportunityList: [
            { name: "On Set Supervision", selected: false, amount: 0 },
            { name: "CG Asset", selected: true, amount: 21250 },
            { name: "Animation", selected: false, amount: 0 },
            { name: "Character Animation", selected: false, amount: 0 },
            { name: "FX", selected: true, amount: 21250 },
            { name: "2D Comp", selected: true, amount: 21250 },
            { name: "CG Integration", selected: true, amount: 21250 }
          ],
        }
      ]
    },
    {
      id: "ahsoka-s2",
      title: "Ahsoka S:2",
      platform: "Disney+",
      category: "VFX",
      services: ["CG Asset", "CG Environments", "FX", "2D Comp", "Virtual Production"],
      thumbnail: "https://image.tmdb.org/t/p/w780/31GIcUUcdQPRkVtmdqgQWJMhXj1.jpg",
      dateAdded: "2026-02-05",
      gradientAngle: 200,
      gradientColors: ["#00EFD8", "#6366F1"],
      totalCost: 550000,
      totalOpportunities: 7,
      totalScenes: 6,
      scenes: [
        {
          id: "ah-scene-1",
          name: "Lightsaber Duel on Peridea",
          duration: "50s",
          scriptPagesStart: 1,
          scriptPagesEnd: 7,
          estimatedLength: "50 sec",
          opportunities: 5,
          complexity: "medium",
          effortHours: 180,
          cost: 130000,
          status: "pending",
          scriptText: "EXT. PERIDEA - ANCIENT RUINS - TWILIGHT\n\nTwo lightsabers clash in the fading light. AHSOKA TANO, dual white blades spinning, presses forward against GRAND ADMIRAL THRAWN's elite guard.\n\nAHSOKA\nThrawn won't escape this time.\n\nShe leaps over a crumbling pillar, blades slicing through stone. The guard stumbles.\n\nSABINE WREN charges in from the flank, her Darksaber igniting.\n\nSABINE\nOn your left!\n\nThey fight back to back. Ancient statues watch silently.",
          opportunityList: [
            { name: "On Set Supervision", selected: false, amount: 0 },
            { name: "CG Asset", selected: true, amount: 26000 },
            { name: "Animation", selected: true, amount: 26000 },
            { name: "Character Animation", selected: false, amount: 0 },
            { name: "FX", selected: true, amount: 26000 },
            { name: "2D Comp", selected: true, amount: 26000 },
            { name: "CG Integration", selected: true, amount: 26000 }
          ],
        },
        {
          id: "ah-scene-2",
          name: "Thrawn's Star Destroyer Bridge",
          duration: "25s",
          scriptPagesStart: 8,
          scriptPagesEnd: 11,
          estimatedLength: "25 sec",
          opportunities: 3,
          complexity: "low",
          effortHours: 60,
          cost: 42000,
          status: "pending",
          scriptText: "INT. STAR DESTROYER - BRIDGE - SPACE\n\nGRAND ADMIRAL THRAWN stands before a massive viewport. Stars streak past in hyperspace.\n\nTHRAWN\nThe Jedi are persistent. But persistence without strategy is merely stubbornness.\n\nCAPTAIN PELLAEON\nSir, we've received word from our agents on Lothal.\n\nTHRAWN\nAnd?\n\nPELLAEON\nThe resistance is growing. Hera Syndulla has rallied the fleet.\n\nThrawn turns slowly, his red eyes gleaming.\n\nTHRAWN\nGood. Let them gather. It makes the harvest... simpler.",
          opportunityList: [
            { name: "On Set Supervision", selected: false, amount: 0 },
            { name: "CG Asset", selected: true, amount: 14000 },
            { name: "Animation", selected: false, amount: 0 },
            { name: "Character Animation", selected: false, amount: 0 },
            { name: "FX", selected: false, amount: 0 },
            { name: "2D Comp", selected: true, amount: 14000 },
            { name: "CG Integration", selected: true, amount: 14000 }
          ],
        },
        {
          id: "ah-scene-3",
          name: "Space Battle Over Lothal",
          duration: "45s",
          scriptPagesStart: 12,
          scriptPagesEnd: 17,
          estimatedLength: "45 sec",
          opportunities: 5,
          complexity: "high",
          effortHours: 200,
          cost: 150000,
          status: "pending",
          scriptText: "EXT. SPACE - LOTHAL ORBIT\n\nX-wings and A-wings engage TIE Defenders in a furious dogfight. HERA SYNDULLA pilots the Ghost through the chaos.\n\nHERA\nAll wings, focus fire on the shield generators!\n\nCHOPPER beeps frantically.\n\nHERA\nI know we're outnumbered, Chop. When has that ever stopped us?\n\nA Star Destroyer looms ahead. Its turbolasers light up the void.\n\nEZRA BRIDGER (on comms)\nGeneral Syndulla, I'm in position. Targeting the ventral array.\n\nHERA\nMay the Force be with you, Ezra.",
          opportunityList: [
            { name: "On Set Supervision", selected: true, amount: 30000 },
            { name: "CG Asset", selected: true, amount: 30000 },
            { name: "Animation", selected: true, amount: 30000 },
            { name: "Character Animation", selected: false, amount: 0 },
            { name: "FX", selected: true, amount: 30000 },
            { name: "2D Comp", selected: true, amount: 30000 },
            { name: "CG Integration", selected: false, amount: 0 }
          ],
        },
        {
          id: "ah-scene-4",
          name: "World Between Worlds",
          duration: "40s",
          scriptPagesStart: 18,
          scriptPagesEnd: 22,
          estimatedLength: "40 sec",
          opportunities: 4,
          complexity: "low",
          effortHours: 150,
          cost: 110000,
          status: "pending",
          scriptText: "INT. WORLD BETWEEN WORLDS - TIMELESS\n\nAhsoka walks along a pathway of light suspended in infinite darkness. Portals shimmer on either side, showing moments from across time.\n\nA familiar voice echoes.\n\nANAKIN (V.O.)\nAhsoka.\n\nShe stops. Through a portal, ANAKIN SKYWALKER appears — young, before the fall.\n\nAHSOKA\nMaster.\n\nANAKIN\nYou've carried this burden long enough. It was never yours to carry.\n\nAHSOKA\nHow do I let go?\n\nANAKIN\n(smiling)\nYou already know.",
          opportunityList: [
            { name: "On Set Supervision", selected: false, amount: 0 },
            { name: "CG Asset", selected: true, amount: 27500 },
            { name: "Animation", selected: false, amount: 0 },
            { name: "Character Animation", selected: true, amount: 27500 },
            { name: "FX", selected: true, amount: 27500 },
            { name: "2D Comp", selected: true, amount: 27500 },
            { name: "CG Integration", selected: false, amount: 0 }
          ],
        },
        {
          id: "ah-scene-5",
          name: "Night Trooper Assault",
          duration: "35s",
          scriptPagesStart: 23,
          scriptPagesEnd: 26,
          estimatedLength: "35 sec",
          opportunities: 5,
          complexity: "medium",
          effortHours: 120,
          cost: 78000,
          status: "pending",
          scriptText: "EXT. PERIDEA - FORTRESS ENTRANCE - NIGHT\n\nNIGHT TROOPERS march in formation, their golden-patched armor gleaming under alien moons. They breach the fortress walls.\n\nSabine ignites the Darksaber. Ezra draws his new lightsaber — green blade humming.\n\nEZRA\nJust like old times?\n\nSABINE\nExcept now I actually know what I'm doing.\n\nThey charge. Sabine deflects blaster bolts while Ezra uses the Force to hurl debris.\n\nAHSOKA drops from above, landing in the center of the troopers.\n\nAHSOKA\nSurrender. This is your only warning.",
          opportunityList: [
            { name: "On Set Supervision", selected: false, amount: 0 },
            { name: "CG Asset", selected: true, amount: 15600 },
            { name: "Animation", selected: true, amount: 15600 },
            { name: "Character Animation", selected: true, amount: 15600 },
            { name: "FX", selected: true, amount: 15600 },
            { name: "2D Comp", selected: false, amount: 0 },
            { name: "CG Integration", selected: true, amount: 15600 }
          ],
        },
        {
          id: "ah-scene-6",
          name: "Thrawn's Defeat",
          duration: "20s",
          scriptPagesStart: 27,
          scriptPagesEnd: 30,
          estimatedLength: "20 sec",
          opportunities: 4,
          complexity: "low",
          effortHours: 50,
          cost: 40000,
          status: "pending",
          scriptText: "INT. STAR DESTROYER - BRIDGE - CONTINUOUS\n\nAlarms blare. The bridge shakes as explosions rock the ship.\n\nPELLAEON\nAdmiral, we've lost the forward shields!\n\nTHRAWN\n(calm, cold)\nRetreat to the Unknown Regions. We will rebuild.\n\nPELLAEON\nBut sir—\n\nTHRAWN\nArt requires patience, Captain. And I am very patient.\n\nThe Star Destroyer jumps to hyperspace, disappearing into the stars.\n\nEXT. SPACE - CONTINUOUS\n\nThe rebel fleet watches it go. A bittersweet victory.",
          opportunityList: [
            { name: "On Set Supervision", selected: true, amount: 10000 },
            { name: "CG Asset", selected: true, amount: 10000 },
            { name: "Animation", selected: false, amount: 0 },
            { name: "Character Animation", selected: false, amount: 0 },
            { name: "FX", selected: false, amount: 0 },
            { name: "2D Comp", selected: true, amount: 10000 },
            { name: "CG Integration", selected: true, amount: 10000 }
          ],
        }
      ]
    }
  ],
  uploadedFiles: []
};
